# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('body', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('news', 'Новость'), ('future_events', 'Предстоящее событие')], default='news', max_length=20)),
            ],
        ),
    ]
