# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171208_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('news', 'Новость'), ('future_events', 'Предстоящее событие')], default='news', max_length=20),
        ),
    ]
