# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171218_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('future_events', 'Предстоящее событие'), ('news', 'Новость')], default='news', max_length=20),
        ),
    ]
