# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180117_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('news', 'Новость'), ('future_events', 'Предстоящее событие')], default='news', max_length=20),
        ),
    ]
