# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180118_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
