# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('event_day', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=6)),
            ],
            options={
                'verbose_name': 'регулярное событие',
                'verbose_name_plural': 'регулярные события',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('news', 'Новость'), ('future_events', 'Предстоящее событие')], default='news', max_length=20),
        ),
    ]
