# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='alias',
            field=models.SlugField(unique=True),
        ),
    ]
