# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20171205_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='show',
            new_name='show_in_menu',
        ),
    ]
