# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_gallery_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/minified/'),
        ),
    ]
