# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20180117_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/minified'),
        ),
    ]
