# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
