# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_auto_20171016_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblebook',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='biblebook',
            name='part_of_bible',
            field=models.CharField(choices=[('ot', 'Ветхий Завет'), ('nt', 'Новый Завет')], default='nt', max_length=2),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio',
            field=models.CharField(max_length=255),
        ),
    ]
