# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0004_auto_20171018_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblebook',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='bible'),
        ),
    ]
