# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0010_ministry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ministry',
        ),
    ]
