# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 09:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0014_auto_20180117_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblebook',
            name='part_of_bible',
            field=models.CharField(choices=[('ot', 'Ветхий Завет'), ('nt', 'Новый Завет')], default='nt', max_length=2),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='chapter_and_verses',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_chapter_and_verses', message='Место Писания должно быть в формате: 1:1, 1:10-21', regex='^\\d{1,3}:\\d{1,3}-{0,1}\\d{0,3}$')]),
        ),
    ]
