# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0017_auto_20180214_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblebook',
            name='part_of_bible',
            field=models.CharField(choices=[('nt', 'Новый Завет'), ('ot', 'Ветхий Завет')], default='nt', max_length=2),
        ),
    ]
