# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-19 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0024_auto_20180220_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='audio',
            field=models.FileField(upload_to='sermons/'),
        ),
    ]
